QuizApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account_app.urls')),
    path('', include('quiz_app.urls')),
]

account_app/urls.py
from django.urls import path
from .views import Login, Register

app_name = 'account'

urlpatterns = [
    path('login', Login.as_view(), name='login_page'),
    path('register', Register.as_view(), name='register_page'),
]

quiz_app/urls.py
from django.urls import path
from.views import Quiz, Result

app_name = 'quiz'
urlpatterns = [
    path('', Quiz.as_view(), name='quiz_page'),
    path('result', Result.as_view(), name='result_page'),
]

account_app/models.py
from django.db import models

# Create your models here.

quiz_app/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    CHOISES = [
        ('option1', 'option1'),
        ('option2', 'option2'),
        ('option3', 'option3'),
        ('option4', 'option4'),
    ]
    question = models.CharField(max_length=50, unique=True)

    option1 = models.CharField(max_length=50)

    option2 = models.CharField(max_length=50)

    option3 = models.CharField(max_length=50)

    option4 = models.CharField(max_length=50)

    answer = models.CharField(max_length=10, choices=CHOISES)

    status = models.BooleanField(default=False, help_text='وضعیت انتشار سوال')

    def __str__(self):
        return self.question


class UserResult(models.Model):
    fullname = models.CharField(max_length=20)

    totall = models.PositiveSmallIntegerField(default=0)

    score = models.PositiveSmallIntegerField(default=0)

    percent = models.FloatField(max_length=5)

    correct = models.PositiveSmallIntegerField(default=0)

    wrong = models.PositiveSmallIntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname

account_app/forms.py
from django import forms
from django.core import validators


class LoginForm(forms.Form):
    fullname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))


class RegisterForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))

    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}),
                             validators=[validators.EmailValidator()])

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    conf_pass = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Password Confirm'}))

account_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.views.generic import View
from .forms import LoginForm, RegisterForm


class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('quiz:quiz_page')
        else:
            form = LoginForm()
            return render(request, 'account_app/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['fullname'], password=cd['password'])

            if user is not None:
                login(request, user)
                return redirect('quiz:quiz_page')
            else:
                form.add_error('fullname', 'Invalid User Data')

        return render(request, 'account_app/login.html', {'form': form})


class Register(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'account_app/register.html', {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            if cd['password'] != cd['conf_pass']:
                form.add_error('password', 'Passwords are not the same !!')
            else:
                fullname = f"{cd['first_name']} {cd['last_name']}"

                user = User.objects.create_user(
                    username=fullname,
                    first_name=cd['first_name'],
                    last_name=cd['last_name'],
                    email=cd['email'],
                    password=cd['password'])

                login(request, user)
                return redirect('quiz:quiz_page')
        else:
            form.add_error('password', 'Invalid Data')

        return render(request, 'account_app/register.html', {'form': form})

quiz_app/views.py
from django.shortcuts import render, redirect, reverse
from .models import Question, UserResult
from django.views.generic import View
from django.contrib import messages


# Create your views here.


class Quiz(View):
    def get(self, request):
        if request.user.is_authenticated:
            user_flag = True

            if UserResult.objects.filter(fullname=request.user.username).exists():
                user_flag = False

            questions = Question.objects.all()

            return render(request, 'index.html', {'questions': questions, 'flag': user_flag})
        else:
            return redirect('account:login_page')

    def post(self, request):
        questions = Question.objects.all()
        fullname = request.user.username
        totall = 0
        score = 0
        correct = 0
        wrong = 0
        for q in questions:
            totall += 1
            if q.answer == request.POST.get(q.question):
                score += 10
                correct += 1
            else:
                wrong += 1
        percent = score / (totall * 10) * 100

        UserResult.objects.create(
            fullname=fullname,
            totall=totall,
            score=score,
            percent=percent,
            correct=correct,
            wrong=wrong,
        )

        return redirect(reverse('quiz:result_page') + f'?fullname={fullname}')


class Result(View):
    def get(self, request):
        if request.user.is_authenticated:
            try:
                fullname = request.GET.get('fullname')
                user_object = UserResult.objects.get(fullname=fullname)
                return render(request, 'quiz_app/result.html', {'user': user_object})
            except:
                return redirect('quiz:quiz_page')
        else:
            return redirect('account:login_page')

account_app/templates/account_app/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-title" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Arone Sadegh">
    <!-- Tab bar name  -->
    <title>Online Quiz</title>
    <!-- Tab bar icon  -->
    <link rel="shortcut icon" href="{% static 'Image/icon.png' %}">
    <!-- Style Sheets -->
    <link rel="stylesheet" href="{% static 'Css/style2.css' %}">
</head>

<body translate="no">

{# Animated Background #}
<div class='box'>
    <div class='wave -one'></div>
    <div class='wave -two'></div>
    <div class='wave -three'></div>
</div>

<div class="login-page">
    <div class="form">
        <form class="login-form" method="post">
            {% csrf_token %}

            {% for error in form.fullname.errors %}
                <p>{{ error }}</p>
            {% endfor %}

            {{ form.fullname }}
            {{ form.password }}

            <button type="submit">login</button>
            <p class="message">Not registered? <a href="{% url 'account:register_page' %}">Create an account</a></p>
        </form>
    </div>
</div>

</body>
</html>

account_app/templates/account_app/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-title" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Arone Sadegh">
    <!-- Tab bar name  -->
    <title>Online Quiz</title>
    <!-- Tab bar icon  -->
    <link rel="shortcut icon" href="{% static 'Image/icon.png' %}">
    <!-- Style Sheets -->
    <link rel="stylesheet" href="{% static 'Css/style2.css' %}">
</head>

<body translate="no">

{# Animated Background #}
<div class='box'>
    <div class='wave -one'></div>
    <div class='wave -two'></div>
    <div class='wave -three'></div>
</div>

<div class="login-page">
    <div class="form">
        <form class="register-form" method="post">
            {% csrf_token %}

            {% for error in form.password.errors %}
                <p>{{ error }}</p>
            {% endfor %}

            {{ form.first_name }}
            {{ form.last_name }}
            {{ form.email }}
            {{ form.password }}
            {{ form.conf_pass }}

            <button type="submit">create</button>
            <p class="message">Already registered? <a href="{% url 'account:login_page' %}">Sign In</a></p>
        </form>
    </div>
</div>

</body>
</html>

quiz_app/templates/quiz_app/result.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-title" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Arone Sadegh">
    <!-- Tab bar name  -->
    <title>Online Quiz</title>
    <!-- Tab bar icon  -->
    <link rel="shortcut icon" href="{% static 'Image/icon.png' %}">
    <!-- Style Sheets -->
    <link rel="stylesheet" href="{% static '/Css/style.css' %}">
    <!-- FontAweome CDN Link for Icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
</head>

<body>

{#Animated Background#}
<div class='box'>
    <div class='wave -one'></div>
    <div class='wave -two'></div>
    <div class='wave -three'></div>
</div>

<!-- Result Box -->
<div class="result_box activeResult">
    <div class="icon">
        {% if user.percent > 80 %}
            <i class="fas fa-crown" style="color: #ffda00"></i>
        {% elif user.percent >= 50 %}
            <i class="fas fa-thumbs-up" style="color: #43b31b"></i>
        {% else %}
            <i class="fas fa-thumbs-down" style="color: #e2192c"></i>
        {% endif %}
    </div>

    <div class="complete_text">آزمون شما به پایان رسید !</div>

    <div class="score_text">
        {% if user.percent > 80 %}
            <span> باریکلا پهلوون ، خوش درخشیدی 🎉</span>
            <hr>
            <span> نام کامل : {{ user.fullname }}</span>
            <span> تعداد کل سوالات : {{ user.totall }}</span>
            <span> امتیاز شما : {{ user.score }}</span>
            <span> درصد شما : {{ user.percent }}</span>
            <span> تعداد سوالات صحیح : {{ user.correct }}</span>
            <span> تعداد سوالات غلط : {{ user.wrong }}</span>
        {% elif user.percent >= 50 %}
            <span> بد نبود ، بیشتر تلاش کن 😎</span>
            <hr>
            <span> نام کامل : {{ user.fullname }}</span>
            <span> تعداد کل سوالات : {{ user.totall }}</span>
            <span> امتیاز شما : {{ user.score }}</span>
            <span> درصد شما : {{ user.percent }}</span>
            <span> تعداد سوالات صحیح : {{ user.correct }}</span>
            <span> تعداد سوالات غلط : {{ user.wrong }}</span>
        {% else %}
            <span> سید خراب کردی ، ازت ناامید شدم 😐</span>
            <hr>
            <span> نام کامل : {{ user.fullname }}</span>
            <span> تعداد کل سوالات : {{ user.totall }}</span>
            <span> امتیاز شما : {{ user.score }}</span>
            <span> درصد شما : {{ user.percent }}</span>
            <span> تعداد سوالات صحیح : {{ user.correct }}</span>
            <span> تعداد سوالات غلط : {{ user.wrong }}</span>
        {% endif %}
    </div>

    <div class="buttons">
        <a class="restart" href="#">دریافت نتایج</a>
        <a class="quit" href="{% url 'quiz:quiz_page' %}">خروج از برنامه</a>
    </div>

</div>

<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-title" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Arone Sadegh">
    <!-- Tab bar name  -->
    <title>Online Quiz</title>
    <!-- Tab bar icon  -->
    <link rel="shortcut icon" href="{% static 'Image/icon.png' %}">
    <!-- Style Sheets -->
    <link rel="stylesheet" href="{% static '/Css/style.css' %}">
    <!-- FontAweome CDN Link for Icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
</head>

<body>
<div class='box'>
    <div class='wave -one'></div>
    <div class='wave -two'></div>
    <div class='wave -three'></div>
</div>
<!-- start Quiz button -->
{% if flag %}
    <div class="start_btn">
        <button>شروع آزمون</button>
    </div>
{% else %}
    <div class="start_btn">
        <a class="restart" href="{% url 'quiz:result_page' %}?fullname={{ request.user.username }}">مشاهده نتیجه</a>
    </div>
{% endif %}

<!-- Info Box -->
<div class="info_box">
    <div class="info-title"><span>قوانین آزمون</span></div>
    <div class="info-list">
        <div class="info">1. شما در کل برای هر سوال <span>10 ثانیه </span> زمان دارید .</div>
        <div class="info">2. هر سوال 10 امتیاز داره .</div>
        <div class="info">3. براساس انتخاب های صحیح شما امتیازتون برآورد میشه .</div>
        <div class="info">4. وقتی زمان به پایان برسه دیگه امکان انتخاب کردن ندارید .</div>
        <div class="info">5. زمانی که آزمون شروع شود امکان خارج شدن ندارید .</div>
        <div class="info">6. سوال های نزده هم به عنوان غلط برآورد میشوند .</div>
        <div class="info">6. هر کاربر فقط یکبار میتونه آزمون بده .</div>
    </div>
    <div class="buttons">
        <button class="quit">خروج</button>
        <button class="restart">ادامه</button>
    </div>
</div>

<!-- Quiz Box -->
<div class="quiz_box">
    <header>
        <div class="title">{{ request.user.username.capitalize }}</div>
        <div class="timer">
            <div class="time_left_txt">Time Left</div>
            <div class="timer_sec"></div>
        </div>
    </header>
    <section class="scroller">
        <form method="post">
            {% csrf_token %}
            {% for q in questions %}
                {% if q.status %}
                    <div class="que_text">
                        <span>{{ q.question }}</span>
                    </div>
                    <div class="option_list">
                        <div class="option"><input type="radio" name="{{ q.question }}" id="radios"
                                                   value="option1">{{ q.option1 }}</div>
                        <div class="option"><input type="radio" name="{{ q.question }}" id="radios"
                                                   value="option2">{{ q.option2 }}</div>
                        <div class="option"><input type="radio" name="{{ q.question }}" id="radios"
                                                   value="option3">{{ q.option3 }}</div>
                        <div class="option"><input type="radio" name="{{ q.question }}" id="radios"
                                                   value="option4">{{ q.option4 }}</div>
                    </div>
                {% endif %}
            {% endfor %}
            <!-- footer of Quiz Box -->
            <footer>
                <div class="total_que">
                    <!-- Here I've inserted Question Count Number from JavaScript -->
                </div>
                <button class="next_btn show" type="submit">پایان آزمون</button>
            </footer>
        </form>
    </section>
</div>

<!-- Inside this JavaScript file I've inserted Questions and Options only -->
<script src="{% static 'js/questions.js' %}"></script>
<!-- Inside this JavaScript file I've coded all Quiz Codes -->
<script src="{% static 'js/script.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</body>
</html>